<!-- wp:group {"metadata":{"name":"Brand assets - Logo section"},"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:heading -->
<h2 class="wp-block-heading">Our logo</h2>
<!-- /wp:heading -->

<!-- wp:image -->
<figure class="wp-block-image"><img alt=""/></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>Download our logo as:</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li class="ba-download">SVG ← make this a download link</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li class="ba-download">EPS ← download link</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li class="ba-download">PNG ← download link</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:heading -->
<h2 class="wp-block-heading">Our icon</h2>
<!-- /wp:heading -->

<!-- wp:image -->
<figure class="wp-block-image"><img alt=""/></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>Download our icon as:</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li class="ba-download">SVG ← download link</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li class="ba-download">EPS ← download link</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li class="ba-download">PNG ← download link</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"name":"Brand assets - Colors section"},"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:heading -->
<h2 class="wp-block-heading">Our brand colors</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>If you're using a block theme, delete the block below and re-add it, it should use the colors from your theme immediately:</p>
<!-- /wp:paragraph -->

<!-- wp:brand-assets/brand-assets {"swatches":[{"name":"Basis","color":"#FFFFFF","cmyk":"0,0,0,0"},{"name":"Contrast","color":"#111111","cmyk":"0,0,0,93"},{"name":"Accent 1","color":"#FFEE58","cmyk":"0,7,65,0"},{"name":"Accent 2","color":"#F6CFF4","cmyk":"0,16,1,4"},{"name":"Accent 3","color":"#503AA8","cmyk":"52,65,0,34"},{"name":"Accent 4","color":"#686868","cmyk":"0,0,0,59"},{"name":"Accent 5","color":"#FBFAF3","cmyk":"0,0,3,2"}]} -->
<div class="wp-block-brand-assets-brand-assets"><div style="--gapWidth:20px;--swatchWidth:150px;--swatchHeight:150px;--borderWidth:1px;--borderRadius:0px;--borderColor:#888888" class="swatch_container"><div class="swatch" style="--swatchColor:#FFFFFF"><span class="name">Basis</span><code>#FFFFFF</code></div><div class="swatch dark" style="--swatchColor:#111111"><span class="name">Contrast</span><code>#111111</code></div><div class="swatch" style="--swatchColor:#FFEE58"><span class="name">Accent 1</span><code>#FFEE58</code></div><div class="swatch" style="--swatchColor:#F6CFF4"><span class="name">Accent 2</span><code>#F6CFF4</code></div><div class="swatch dark" style="--swatchColor:#503AA8"><span class="name">Accent 3</span><code>#503AA8</code></div><div class="swatch dark" style="--swatchColor:#686868"><span class="name">Accent 4</span><code>#686868</code></div><div class="swatch" style="--swatchColor:#FBFAF3"><span class="name">Accent 5</span><code>#FBFAF3</code></div></div></div>
<!-- /wp:brand-assets/brand-assets --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"name":"Brand assets - Fonts section"},"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:heading -->
<h2 class="wp-block-heading">Our fonts</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><strong>Note:</strong> It's usually helpful to give visitors the font names somewhere too!</p>
<!-- /wp:paragraph -->

<!-- wp:group {"metadata":{"name":"HTML element examples"},"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:heading {"level":1} -->
<h1 class="wp-block-heading">This is an H1</h1>
<!-- /wp:heading -->

<!-- wp:heading -->
<h2 class="wp-block-heading">This is an H2</h2>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">This is an H3</h3>
<!-- /wp:heading -->

<!-- wp:heading {"level":4} -->
<h4 class="wp-block-heading">This is an H4</h4>
<!-- /wp:heading -->

<!-- wp:heading {"level":5} -->
<h5 class="wp-block-heading">This is an H5</h5>
<!-- /wp:heading -->

<!-- wp:heading {"level":6} -->
<h6 class="wp-block-heading">This is an H6</h6>
<!-- /wp:heading -->

<!-- wp:paragraph {"metadata":{"name":"Normal text"}} -->
<p>This is normal text</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"metadata":{"name":"Bold text"}} -->
<p><strong>This is bold text</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"metadata":{"name":"Italic text"}} -->
<p><em>This is italic text</em></p>
<!-- /wp:paragraph -->

<!-- wp:table -->
<figure class="wp-block-table"><table class="has-fixed-layout"><thead><tr><th>Table heading</th></tr></thead><tbody><tr><td>Table cell</td></tr></tbody><tfoot><tr><td>Table footer</td></tr></tfoot></table></figure>
<!-- /wp:table --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:paragraph -->
<p>If you have any questions on how to use our brand identity, please contact us!</p>
<!-- /wp:paragraph -->
